// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */

const sidebars = {
  tutorialSidebar: [
    'intro',

    {
      type: 'category',
      label: 'Python 🐍',
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: 'Python',
        },
      ],
    },

    {
      type: 'category',
      label: 'Web 🌐',
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: 'Web',
        },
      ],
    },

    {
      type: 'category',
      label: 'AR-IO 🛰️',
      collapsed: true,
      items: [
        {
          type: 'autogenerated',
          dirName: 'AR-IO',
        },
      ],
    },
  ],
};

export default sidebars;