// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */

const sidebars = {
  tutorialSidebar: [
    // ============================================================
    // GIỚI THIỆU
    // ============================================================
    'intro',

    // ============================================================
    // PYTHON
    // ============================================================
    {
      type: 'category',
      label: 'Python 🐍',
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: 'Python',
        },
      ],
    },

    // ============================================================
    // WEB DEVELOPMENT
    // ============================================================
    {
      type: 'category',
      label: 'Web Development 🌐',
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: 'Web',
        },
      ],
    },

    // ============================================================
    // GIÁO DỤC
    // ============================================================
    {
      type: 'category',
      label: 'Giáo dục 🎓',
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: 'giao-duc',
        },
      ],
    },

    // ============================================================
    // STEM & CÔNG NGHỆ
    // ============================================================
    {
      type: 'category',
      label: 'STEM & Công nghệ 🔬',
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: 'STEM',
        },
      ],
    },

    // ============================================================
    // KINH NGHIỆM
    // ============================================================
    {
      type: 'category',
      label: 'Kinh nghiệm 💡',
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: 'kinh-nghiem',
        },
      ],
    },

    // ============================================================
    // DỰ ÁN
    // ============================================================
    {
      type: 'category',
      label: 'Dự án 🚀',
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: 'du-an',
        },
      ],
    },

    // ============================================================
    // AR-IO
    // ============================================================
    {
      type: 'category',
      label: 'AR-IO 🛰️',
      collapsed: true,
      items: [
        {
          type: 'autogenerated',
          dirName: 'AR-IO',
        },
      ],
    },
  ],
};

export default sidebars;